defaults:
  - config
  - _self_

experiment_name: resnet18_cifar10

model:
  _target_: src.module.resnet18.ResNet18Classifier
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-3
    weight_decay: 0
  num_classes: 10

datamodule:
  _target_: src.datamodule.default.cifar10.CIFAR10DataModule